services:
  anztbot:
    build: .
    container_name: anztbot
    ports:
      - "5000:5000"
    volumes:
      # Mount config files
      - ./settings.jsonc:/app/settings.jsonc:ro
      - ./client_secret.json:/app/client_secret.json:ro
    restart: on-failure:3